pip show	aiohttp	>>	licenseValidation.txt
pip show	altgraph	>>	licenseValidation.txt
pip show	async-timeout	>>	licenseValidation.txt
pip show	attrs	>>	licenseValidation.txt
pip show	boto3	>>	licenseValidation.txt
pip show	botocore	>>	licenseValidation.txt
pip show	cachetools	>>	licenseValidation.txt
pip show	CD	>>	licenseValidation.txt
pip show	certifi	>>	licenseValidation.txt
pip show	cffi	>>	licenseValidation.txt
pip show	chardet	>>	licenseValidation.txt
pip show	click	>>	licenseValidation.txt
pip show	docutils	>>	licenseValidation.txt
pip show	easygui	>>	licenseValidation.txt
pip show	et-xmlfile	>>	licenseValidation.txt
pip show	Flask	>>	licenseValidation.txt
pip show	Flask-Cors	>>	licenseValidation.txt
pip show	Flask-SocketIO	>>	licenseValidation.txt
pip show	future	>>	licenseValidation.txt
pip show	gensim	>>	licenseValidation.txt
pip show	get	>>	licenseValidation.txt
pip show	gevent	>>	licenseValidation.txt
pip show	google-api-core	>>	licenseValidation.txt
pip show	google-auth	>>	licenseValidation.txt
pip show	google-cloud-core	>>	licenseValidation.txt
pip show	google-cloud-storage	>>	licenseValidation.txt
pip show	google-resumable-media	>>	licenseValidation.txt
pip show	googleapis-common-protos	>>	licenseValidation.txt
pip show	greenlet	>>	licenseValidation.txt
pip show	idna	>>	licenseValidation.txt
pip show	itsdangerous	>>	licenseValidation.txt
pip show	jdcal	>>	licenseValidation.txt
pip show	Jinja2	>>	licenseValidation.txt
pip show	jmespath	>>	licenseValidation.txt
pip show	joblib	>>	licenseValidation.txt
pip show	MarkupSafe	>>	licenseValidation.txt
pip show	multidict	>>	licenseValidation.txt
pip show	numpy	>>	licenseValidation.txt
pip show	openpyxl	>>	licenseValidation.txt
pip show	pandas	>>	licenseValidation.txt
pip show	pefile	>>	licenseValidation.txt
pip show	Pillow	>>	licenseValidation.txt
pip show	post	>>	licenseValidation.txt
pip show	protobuf	>>	licenseValidation.txt
pip show	public	>>	licenseValidation.txt
pip show	pyasn1	>>	licenseValidation.txt
pip show	pyasn1-modules	>>	licenseValidation.txt
pip show	pycparser	>>	licenseValidation.txt
pip show	pyee	>>	licenseValidation.txt
pip show	PyInstaller	>>	licenseValidation.txt
pip show	python-dateutil	>>	licenseValidation.txt
pip show	python-engineio	>>	licenseValidation.txt
pip show	python-socketio	>>	licenseValidation.txt
pip show	pytz	>>	licenseValidation.txt
pip show	pywin32	>>	licenseValidation.txt
pip show	pywin32-ctypes	>>	licenseValidation.txt
pip show	query-string	>>	licenseValidation.txt
pip show	reportlab	>>	licenseValidation.txt
pip show	request	>>	licenseValidation.txt
pip show	requests	>>	licenseValidation.txt
pip show	rsa	>>	licenseValidation.txt
pip show	s3transfer	>>	licenseValidation.txt
pip show	scipy	>>	licenseValidation.txt
pip show	six	>>	licenseValidation.txt
pip show	slackcli	>>	licenseValidation.txt
pip show	slackclient	>>	licenseValidation.txt
pip show	slackclient-cli	>>	licenseValidation.txt
pip show	slackeventsapi	>>	licenseValidation.txt
pip show	smart-open	>>	licenseValidation.txt
pip show	urllib3	>>	licenseValidation.txt
pip show	websocket-client	>>	licenseValidation.txt
pip show	Werkzeug	>>	licenseValidation.txt
pip show	XlsxWriter	>>	licenseValidation.txt
pip show	yarl	>>	licenseValidation.txt
